version: '3.8'

networks:
  blog-app:
    driver: bridge

services:
  app:
    build: .
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    
    depends_on: 
      postgres:
        condition: service_healthy
    environment:
      APP_NAME: Laravel
      APP_ENV: local

      DB_CONNECTION: pgsql  # Change to PostgreSQL
      DB_HOST: postgres     # Service name of the PostgreSQL container
      DB_PORT: 5432         # Default PostgreSQL port
      DB_DATABASE: laravel_blog
      DB_USERNAME: postgres_user  # Your PostgreSQL username
      DB_PASSWORD: db_password   # Your PostgreSQL password

    entrypoint: /bin/bash /var/www/html/entrypoint.sh
    
    networks:
      - blog-app

  postgres:
    image: postgres:13
    container_name: postgres
    platform: linux/amd64
    environment:
      POSTGRES_DB: laravel_blog
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: db_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres_user", "-d", "laravel_blog", "-h", "localhost"]
      interval: 10s
      retries: 5

    networks:
      - blog-app

volumes:
  db_data:
